package com.example.Student_Library_Management_System.Service;

import com.example.Student_Library_Management_System.DTOs.StudentUpdateMobRequestDTo;
import com.example.Student_Library_Management_System.Enum.CardStatus;
import com.example.Student_Library_Management_System.Models.Card;
import com.example.Student_Library_Management_System.Models.Student;
import com.example.Student_Library_Management_System.Repository.StudentRepository;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

@Service
public class StudentService {

   @Autowired
    StudentRepository studentRepository;

   public String createStudent(Student student){
       // card should be autogenerated when this function is called

       Card card = new Card();
       card.setCardStatus(CardStatus.ACTIVATED);
       card.setStudent(student); // foreign key attribute

       student.setCard(card);

       studentRepository.save(student); // by cascading child will automatically be saved
      return "Created ";
   }

   public String findNameByEmail(String email){

     Student student = studentRepository.findByEmail(email);

     return student.getName();
   }

   public String updateMobNumber(StudentUpdateMobRequestDTo studentUpdateMobRequestDTo) {

      Student student = studentRepository.findById(studentUpdateMobRequestDTo.getId()).get();
      student.setMobNo(studentUpdateMobRequestDTo.getMobNo());

      studentRepository.save(student);

       return "Updated Mobile Number Successfully";
   }
}
